image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Build and Deploy to Supply Frontend
          deployment: Production
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $USER
                SERVER: $SUPPLY_SERVER
                COMMAND: '/home/team22/supplyScriptFE.sh'
